---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 8033
    protocol: TCP
    name: health
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: myrepo/nginx-k8s:latest
        env:
        - name: PROXY_DOMAIN
          value: kubernetes.mydomain.tld
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8033
          name: healthz
